### ISSUE TITLE
Organize the insightful codes and uses in the published theses from ZJUEarthData

### ISSUE THREAD

**Issue by SanyHe** [ZJUEarthData/geochemistrypi#10]
Notes:
+ pair the codes scripts with the corresponding uses

**Comment by Lyuyangdaisy** [comment]
This ppt files contains all kinds of geology figures in five researchers' works. But some of figures are from excel or origin apps. [地球化学图-Geochem py-总.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/8308657/-Geochem.py-.pptx)
1. Ben‘s project codes: https://github.com/ZJUEarthData/BenQin_mantle-matesomatism-machine-learning
2. Lei's project codes：https://github.com/ZJUEarthData/Carbon-Predictions
3. Huang's project codes：https://github.com/ZJUEarthData/pyro_processor/tree/main/Fe3_calculation_program
4. Chen's project codes： https://doi.org/10.5281/zenodo.5339000
5. Wang's project codes：https://github.com/luwang9103/MPR-Li-mica.git

**Comment by Lyuyangdaisy** [comment]
以上项目代码链接里，多数为机器学习模型代码，少数为地球化学作图代码。这个word文件列举了这五个项目的代码目录。[以前项目的代码目录.docx](https://github.com/ZJUEarthData/geochemistrypy/files/8308774/default.docx)

**Comment by Lyuyangdaisy** [comment]
代码需求
1.地球化学代码图需求：
二元/三元相图的数据投图（最好可以自定义三个端元及刻度；可自带一些模板也可自定义模板）
用于能够直接在Geochemistry py网页界面直接了解数据形态并及时作处下一步决策，而不用将数据导入excel或origin等软件再作图。
2.其他：
高斯混合模型代码

**Comment by Lyuyangdaisy** [comment]
地球化学图分为通用图和机器学习分析图两类，其中通用图包含二元图和三元图两类（解决方式：提供白底二元图和三元图，辅助功能--能够变换不同数据形式）。
[Uploading 地球化学图-二元、三元图解决.docx…]

**Comment by Lyuyangdaisy** [comment]
Pyrolite数据库的Docstring调研内容：
[Docstring.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/8500041/Docstring.pptx)
