### ISSUE TITLE
Research on hyper-parameters searching

### ISSUE THREAD

**Issue by SanyHe** [ZJUEarthData/geochemistrypi#29]
Find the feasible ways to implement hyper-parameters search.
Note:
+ Proper Algorithms or Mature Packages

**Comment by WenyuMolly** [comment]
1 Data selection
[data-selection分享 - .pptx](https://github.com/ZJUEarthData/geochemistrypy/files/8837088/data-selection.-.pptx)

**Comment by WenyuMolly** [comment]
**2 Overfitting&Hyperparamete-selection**
[overfitting&hyparameter-selection分享.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/8837089/overfitting.hyparameter-selection.pptx)

**Comment by WenyuMolly** [comment]
**3 Hyperparameter collection from ZJUEarthData Project**
[hyperparameters调研.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/8837096/hyperparameters.pptx)

**Comment by WenyuMolly** [comment]
**4 AutoMl_Frameworks**
[AutoML_Frameworks.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/8837100/AutoML_Frameworks.pptx)

**Comment by WenyuMolly** [comment]
**4 AutoMl_Frameworks**
[AutoML_Frameworks.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/8837100/AutoML_Frameworks.pptx)
