### ISSUE TITLE
Research on docstring template

### ISSUE THREAD

**Issue by SanyHe** [ZJUEarthData/geochemistrypi#30]
Set up the proper docsting template for our project.
Note:
+ refer to other packages
+ build our own template

**Comment by Lyuyangdaisy** [comment]
Pyrolite数据库Docstring调研情况
[Docstring-Pyrolite调研.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/8620616/Docstring-Pyrolite.pptx)
Geochemistry Py的Dostring初代书写模板
[Docstring模板-初代.pdf](https://github.com/ZJUEarthData/geochemistrypy/files/8620625/Docstring.-.pdf)
[Docstring模板-初代.docx](https://github.com/ZJUEarthData/geochemistrypy/files/8620629/Docstring.-.docx)
