### ISSUE TITLE
Dependent packages download and management

### ISSUE THREAD

**Issue by SanyHe** [ZJUEarthData/geochemistrypi#31]
Find the proper ways or tools to solve the problem caused by dependent package on different operating system.
Note:
+ Priority: Windows > Mac > Linux

**Comment by PotatoXi** [comment]
On the Window11 system,  install all packages by ’‘requirements .txt ’
[win11_install_by_requirements.md](https://github.com/ZJUEarthData/geochemistrypy/files/8629320/win11_install_by_requirements.md)

**Comment by PotatoXi** [comment]
Packaging and uploading in Pypi
Creating and uploading in Read the Docs

**Comment by PotatoXi** [comment]
[Pypi上传package步骤.md](https://github.com/ZJUEarthData/geochemistrypy/files/8749586/Pypi.package.md)

**Comment by Qinyh1** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我是QYH~您的邮件我已经收到~

**Comment by PotatoXi** [comment]
在windows 系统下，清屏用到的代码：os.system('cls')

**Comment by Qinyh1** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我是QYH~您的邮件我已经收到~
