### ISSUE TITLE
New research for online documents 

### ISSUE THREAD

**Issue by ZJU-Earth-Data** [ZJUEarthData/geochemistrypi#63]
New research for online documents of python package and open apps

**Comment by ZJU-Earth-Data** [comment]
[在线文档调研.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/9333717/default.pptx)
the catalogues for python package and open app

**Comment by Lyuyangdaisy** [comment]
[GeoPy Tool.docx](https://github.com/ZJUEarthData/geochemistrypy/files/9439804/GeoPy.Tool.docx)
[GeoPy Tool思维导图.pdf](https://github.com/ZJUEarthData/geochemistrypy/files/9439805/GeoPy.Tool.pdf)
开源软件GeoPy Tool的在线文档调研情况。此软件基于python开发，偏向地化中的地质作图和数据处理。使用PyQt5作为GUI，pandas导入数据，numpy和scipy进行数据拟合计算，sklearn实现机器学习算法。

**Comment by Lyuyangdaisy** [comment]
[Pyrolite代码库出图种类及功能.docx](https://github.com/ZJUEarthData/geochemistrypy/files/9439831/Pyrolite.docx)
[Pyrolite思维导图.pdf](https://github.com/ZJUEarthData/geochemistrypy/files/9439833/Pyrolite.pdf)
代码包Pyrolite的在线文档调研情况。此软件基于python开发，主要用于地球化学领域中的作图和数据计算，出图种类很全。

**Comment by Kaixin7** [comment]
开源软件GeoNetwork在线文档调研情况。该软件在Java8环境下运行，主要用于地理空间数据的搜索、管理和成图，提供了强大的元数据编辑和搜索功能，以及一个交互式网络地图查看器，可以在成图后发布与他人共享地图，网站上提供了许多地理空间数据图，可以下载并使用。
[GeoNetwork.pdf](https://github.com/ZJUEarthData/geochemistrypy/files/9557757/GeoNetwork.pdf)

**Comment by WenyuMolly** [comment]
Mintpy在线文件调研
[Mintpy文档调研.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/9661625/Mintpy.pptx)

**Comment by WenyuMolly** [comment]
online_documentation_v1
[online_documentation_9_28.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/9661853/online_documentation_9_28.pptx)

**Comment by Lyuyangdaisy** [comment]
online_documentation_v1的初步任务分配
[online_documentation_10.2.pptx](https://github.com/ZJUEarthData/geochemistrypy/files/9692772/online_documentation_10.2.pptx)
